### ISSUE TITLE
Private scoping error xcode9

### ISSUE THREAD

**Issue by MattSich** [sean7512/RestEssentials#14] opened 2017-09-25 20:33 UTC
If trying to use restEssentials in my project, I get an error in JSON.swift at line 192
![screen shot 2017-09-25 at 4 29 39 pm](https://user-images.githubusercontent.com/6378097/30829573-2673bade-a20f-11e7-8b45-f86f0a0cb19a.png)

raw should be set to fileprivate I believe 

@sean7512

**Comment by sean7512** [comment] 2017-09-28 10:39
@MattSich @aravasio I cannot reproduce this.  I have even created new test projects from scratch to no avail.

What version of cocoapods are you using? Ensure you have the latest version that supports Xcode 9 and swift 4.

**Comment by sean7512** [comment] 2017-09-28 10:48
@MattSich @aravasio Under the Pods project, select the RestEssentials target and then go to build settings and ensure that the "Swift Language Version" is set to 4.0  If you are not using the latest Cocoapods, you WILL have to set this, as Cocoapods 1.3.1 added support for Xcode 9 and Swift 4.  I would recommend updating cocoapods and re-installing your pods.  If you can't do that then try changing the swift language manually.

![restessentials](https://user-images.githubusercontent.com/3290282/30962718-e53d5a82-a418-11e7-93a7-02886162e084.png)

**Comment by sean7512** [comment] 2017-09-28 10:53
@MattSich As of Swift4, private works in the same file for extensions.  That is documented here: 

https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/AccessControl.html 

"Private access restricts the use of an entity to the enclosing declaration, and to extensions of that declaration that are in the same file. Use private access to hide the implementation details of a specific piece of functionality when those details are used only within a single declaration."

**Comment by aravasio** [comment] 2017-09-28 17:26
@sean7512 you're totally right. It was my Cocoapods that was outdated. Either proposed solution works. This should be considered resolved and be closed.

**Comment by sean7512** [comment] 2017-09-29 10:28
@aravasio glad that fixed it for you, I will close this issue now.

**Closed as completed by sean7512** 2017-09-29 10:28 UTC
